name: "yolov8"
platform: "tensorrt_plan"
max_batch_size: 2

dynamic_batching {
  preferred_batch_size: [ 2 ]
  max_queue_delay_microseconds: 50000 
}

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 736, 1280 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]